### ISSUE TITLE
[1.2.1 mc 1.11.2] client crash while placing little tiles version of opf

### ISSUE THREAD

**Issue by kreezxil** [CreativeMD/OnlinePictureFrame#2]
client crash report:

https://gist.github.com/kreezxil/e2ef01ace37240513df148effc4e19cb

Was trying to place the little tiles version of the opf on a single glass pane post.

A glass pane post is what you get when there are no other blocks for the glass pane to connect to on any of the cardinal sides (N,S,E,W).

**Comment by kreezxil** [comment]
Just noticed on the server, probably the same thing from the client, altho the server did not crash

```
[10:07:07] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field com.creativemd.littletiles.common.utils.LittleTileBlock.meta from class com.creativemd.opf.little.LittlePlaceOpPreview
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalAccessError: tried to access field com.creativemd.littletiles.common.utils.LittleTileBlock.meta from class com.creativemd.opf.little.LittlePlaceOpPreview
        at com.creativemd.opf.little.LittlePlaceOpPreview.placeTile(LittlePlaceOpPreview.java:59) ~[LittlePlaceOpPreview.class:?]
        at com.creativemd.littletiles.common.items.ItemBlockTiles.placeTiles(ItemBlockTiles.java:340) ~[ItemBlockTiles.class:?]
        at com.creativemd.littletiles.common.items.ItemBlockTiles.placeBlockAt(ItemBlockTiles.java:413) ~[ItemBlockTiles.class:?]
        at com.creativemd.littletiles.common.packet.LittlePlacePacket.executeServer(LittlePlacePacket.java:98) ~[LittlePlacePacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:122) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by kreezxil** [comment]
Ok, tried logging back on, apparently the mini-block version placed but now the client is kicked-crashed to the desktop with a render error.

https://gist.github.com/kreezxil/b5dee350462bd4245877cf85cd3ca4ae

**Comment by kreezxil** [comment]
oops, hit the wrong button just now. :(

**Comment by CreativeMD** [comment]
Sorry, OnlinePictureFrame was not ready for the newest LittleTiles version yet. It is fixed now.
