### ISSUE TITLE
[BUG] Optifine Connected Textures causes crash

### ISSUE THREAD

**Issue by xunto** [CreativeMD/OnlinePictureFrame#26]
Hi! Great mod! I think I found some problem with it though.

If you place two picture frames near while having resourcepack and with connected textures (optifine) enabled, it hangs the client (very badly).

- Minecraft 1.12
- Forge OptiFine_1.12.2_HD_U_E3.jar
- CreativeCore_v1.9.39_mc1.12.2.jar
- OnlinePicFrame_v1.4.23_mc1.12.2.jar
- ConquestReforged-3.0.2-mc1.12.2.jar with its texturepack for connected textures

You should place them like this for this bug to appear (disabled connected textures to show).
![2019-02-09_10 07 43](https://user-images.githubusercontent.com/5288053/52517846-ab09d700-2c52-11e9-81ee-9bb92e42e887.png)

Errors in console (they appear as in infinite loop):
```
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1581)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1537)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1517)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.getConnectedTextureHorizontal(ConnectedTextures.java:1641)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:562)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:382)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:311)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:122)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at java.lang.reflect.Method.invoke(Method.java:498)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at com.creativemd.creativecore.client.mods.optifine.OptifineHelper.getRenderQuads(OptifineHelper.java:108)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at com.creativemd.creativecore.client.rendering.RenderCubeObject.getBakedQuad(RenderCubeObject.java:271)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at com.creativemd.creativecore.client.rendering.RenderCubeObject.getBakedQuad(RenderCubeObject.java:275)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:118)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:219)
[09:49:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:   at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
```

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report?

**Comment by xunto** [comment]
@CreativeMD [latest.log](https://github.com/CreativeMD/OnlinePictureFrame/files/2849944/latest.log)

**Comment by xunto** [comment]
Any luck?

**Comment by CreativeMD** [comment]
I don't have any time at the moment, sorry :( I have to learn for exams, I will have plenty of time next week.

**Comment by xunto** [comment]
Ah, I understand. Had 2 sleepless nights that weekend. So no problem, thanks. I'll wait.

**Comment by CreativeMD** [comment]
Does this crash still happen if LittleTiles is installed?

**Comment by xunto** [comment]
I'll check.

**Comment by CreativeMD** [comment]
Update CreativeCore to v1.9.41 and it should work.

**Comment by xunto** [comment]
@CreativeMD Sorry, had some exams too. :D

I updated CreativeCore and installed LittleTiles but crash still happens.

**Comment by xunto** [comment]
Have you tried to install mod I have? And crash doesn't happen to you? Just want to make sure.

**Comment by CreativeMD** [comment]
Works just fine, using:
ConquestReforged-3.0.2-mc1.12.2.jar
CreativeCore_v1.9.41_mc1.12.2.jar
OptiFine_1.12.2_HD_U_E3.jar
OnlinePicFrame_v1.4.23_mc1.12.2.jar

**Comment by xunto** [comment]
Wait, yes it does work! But only after I deleted little tiles. :D

**Comment by CreativeMD** [comment]
Test it with LittleTiles and it still works just fine.
