### ISSUE TITLE
Could not download image - java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by DehlakDrake** [CreativeMD/OnlinePictureFrame#48]
With CreativeCore (v1.10.10 - MC1.12.2) and OPF (v1.4.37 - MC1.12.2), I am unable to download any online image onto the online picture frame. Images successfully load when stored locally, but nothing online works.

The error that occurs is as follows:
```
[16:47:06] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/INFO] [NonUpdate]: Release: i.imgur.com:-1
[16:47:06] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/INFO] [NonUpdate]: Check: i.imgur.com:443
[16:47:06] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/INFO] [NonUpdate]: Redirect: i.imgur.com -> 0.0.0.0
[16:47:06] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/INFO] [NonUpdate]: Release: 0.0.0.0:443
[16:47:06] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/INFO] [NonUpdate]: Release: 0.0.0.0:443
[16:47:06] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/INFO] [NonUpdate]: Release: <computername>:-1
[16:47:07] [OPF Download "https://i.imgur.com/MbTJk8F.jpg"/ERROR] [com.creativemd.opf.OPFrame]: An exception occurred while loading OPFrame image
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_251]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_251]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_251]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_251]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_251]
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_251]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_251]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_251]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_251]
	at com.creativemd.opf.client.DownloadThread.load(DownloadThread.java:149) ~[DownloadThread.class:?]
	at com.creativemd.opf.client.DownloadThread.run(DownloadThread.java:84) [DownloadThread.class:?]
[16:47:07] [Client thread/ERROR] [com.creativemd.opf.OPFrame]: Could not load image of BlockPos{x=-106, y=69, z=135} download.exception.invalid
```

**Comment by CreativeMD** [comment]
Not sure if that is an issue of OnlinePictureFrame. Maybe the game has no internet access, don't see anything I can do.

**Comment by CreativeMD** [comment]
I will close this issue for now, if you have more information just let me now.
