### ISSUE TITLE
Pictures can't load

### ISSUE THREAD

**Issue by LixYt** [CreativeMD/OnlinePictureFrame#50]
Hi there !

Nice work on this mod but since today, i got an isssue. Some pictures does not load anymore...
I try to update the mod to latest version (1.4.39 using curseforge) but did not change a thing.

Pictures are accessible from browser with http and https access.

Here is what i got in debug.log :
`
[13:58:11] [OPF Download "https://lix.yt/files/SW_RPG/board1.jpg"/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[13:58:11] [OPF Download "https://lix.yt/files/SW_RPG/board1.jpg"/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.opf.client.DownloadThread.run(DownloadThread.java:118)
[13:58:12] [OPF Download "https://lix.yt/files/SW_RPG/board4.jpg"/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[13:58:12] [OPF Download "https://lix.yt/files/SW_RPG/board4.jpg"/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.opf.client.DownloadThread.run(DownloadThread.java:118)
[13:58:13] [OPF Download "https://lix.yt/files/SW_RPG/gray_concrete_powder_28par28.png"/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[13:58:13] [OPF Download "https://lix.yt/files/SW_RPG/gray_concrete_powder_28par28.png"/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.opf.client.DownloadThread.run(DownloadThread.java:118)

`

Any idea ?

Regards
Lix

**Comment by CreativeMD** [comment]
Can you try out the newest version and see if it's fixed?

**Comment by LixYt** [comment]
That's much better thanks a lot.

Still a little issue that I fixed on my side when there is a URL redirection done by the server.

For instance, this URL won't load the picture : _http_://www.lix.yt/files/SW_RPG/wall_hangar_bay_dark_50_100.png
But this one will : _http**s**_://www.lix.yt/files/SW_RPG/wall_hangar_bay_dark_50_100.png

My server redirects all HTTP request to HTTPS and it looks like some way, the mod don't like that ^^
As said. Now it work by settings hard HTTPS instead of HTTP so for my it's OK ;-)

Corresponding logs with HTTP redirected to HTTPS : 
[11:06:21] [Client thread/ERROR] [com.creativemd.opf.OPFrame]: Could not load image of BlockPos{x=5055, y=63, z=4962} download.exception.gif
[11:06:22] [Client thread/ERROR] [com.creativemd.opf.OPFrame]: Could not load image of BlockPos{x=5055, y=63, z=4962} download.exception.gif
[11:06:22] [Client thread/ERROR] [com.creativemd.opf.OPFrame]: Could not load image of BlockPos{x=5055, y=63, z=4962} download.exception.gif
[11:06:30] [Client thread/ERROR] [com.creativemd.opf.OPFrame]: Could not load image of BlockPos{x=5055, y=63, z=4962} download.exception.gif

**Comment by CreativeMD** [comment]
Good to hear that :D yeah those redirects are not that easy to do apparently.

**Comment by LixYt** [comment]
If you need to test it. feel free to ask or to use my server url/files. ;-)

I'm using it to build a RPG tabletop map in Star Wars univers and it's helps me THAT MUCH !
