### ISSUE TITLE
Crash when opening backpack and browsing

### ISSUE THREAD

**Issue by icyqwq** [CreativeMD/OnlinePictureFrame#57]
When I press E to open the backpack, switch to the decoration tab and scroll down to the Online picture frame item, the game crashed.

Here is the mod installed
![image](https://user-images.githubusercontent.com/24635694/96554596-505ec480-12e9-11eb-85bd-da7099cec5db.png)
![image](https://user-images.githubusercontent.com/24635694/96554470-2907f780-12e9-11eb-8054-41bf6598d7e9.png)
![image](https://user-images.githubusercontent.com/24635694/96554510-34f3b980-12e9-11eb-91ad-97dc71689414.png)

Here is the log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.29_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 10/20/20 3:27 PM
Description: Rendering item

java.lang.ClassCastException: com.creativemd.creativecore.client.rendering.RenderCubeObject cannot be cast to com.creativemd.creativecore.client.rendering.RenderBox
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:80)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:159)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:80)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:159)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: net.minecraft.item.ItemBlock@72bd8702
	Registry Name: opframe:opframe
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (197, 117). Absolute: (395, 245)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HeavenTyh'/356, l='MpServer', x=133.20, y=64.00, z=-57.15]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (136,64,-60), Chunk: (at 8,4,4 in 8,-4; contains blocks 128,0,-64 to 143,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1027 game time, 1027 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityChicken['鸡'/129, l='MpServer', x=89.91, y=63.00, z=-125.87], EntityChicken['鸡'/130, l='MpServer', x=81.50, y=64.00, z=-116.22], EntityChicken['鸡'/131, l='MpServer', x=87.50, y=67.00, z=-106.50], EntityChicken['鸡'/132, l='MpServer', x=82.32, y=72.00, z=-104.48], EntityChicken['鸡'/133, l='MpServer', x=84.15, y=72.00, z=-104.58], EntityWitch['女巫'/134, l='MpServer', x=82.50, y=18.00, z=-27.50], EntitySheep['羊'/135, l='MpServer', x=83.50, y=68.00, z=-6.50], EntitySheep['羊'/136, l='MpServer', x=87.22, y=67.00, z=-14.21], EntitySheep['羊'/137, l='MpServer', x=84.49, y=67.00, z=-8.69], EntitySheep['羊'/138, l='MpServer', x=81.95, y=67.00, z=-12.60], EntitySkeleton['骷髅'/139, l='MpServer', x=89.26, y=29.00, z=20.54], EntitySkeleton['骷髅'/144, l='MpServer', x=107.48, y=45.00, z=-131.70], EntitySkeleton['骷髅'/145, l='MpServer', x=106.50, y=46.00, z=-134.50], EntitySkeleton['骷髅'/146, l='MpServer', x=103.50, y=46.00, z=-133.50], EntityChicken['鸡'/147, l='MpServer', x=101.50, y=63.00, z=-134.50], EntitySkeleton['骷髅'/148, l='MpServer', x=104.52, y=43.00, z=18.72], EntitySquid['鱿鱼'/167, l='MpServer', x=128.38, y=61.05, z=-13.58], EntitySpider['蜘蛛'/176, l='MpServer', x=139.00, y=35.00, z=-115.95], EntityZombie['僵尸'/177, l='MpServer', x=137.22, y=54.00, z=-125.49], EntityCreeper['爬行者'/178, l='MpServer', x=136.70, y=35.00, z=-108.21], EntityHorse['马'/179, l='MpServer', x=132.48, y=78.00, z=-72.71], EntityCreeper['爬行者'/435, l='MpServer', x=180.50, y=20.00, z=-109.50], EntityHorse['马'/180, l='MpServer', x=143.00, y=75.00, z=-68.89], EntityItem['item.item.leather'/181, l='MpServer', x=139.53, y=64.00, z=-60.88], EntityItem['item.item.leather'/182, l='MpServer', x=137.58, y=66.00, z=-59.88], EntitySquid['鱿鱼'/183, l='MpServer', x=129.60, y=61.36, z=-7.39], EntityItem['item.item.seeds'/440, l='MpServer', x=122.86, y=64.26, z=-36.95], EntitySpider['蜘蛛'/189, l='MpServer', x=157.82, y=15.00, z=-126.22], EntityBat['蝙蝠'/190, l='MpServer', x=153.75, y=12.10, z=-104.25], EntityBat['蝙蝠'/191, l='MpServer', x=145.58, y=15.04, z=-97.43], EntityBat['蝙蝠'/192, l='MpServer', x=147.77, y=15.39, z=-95.37], EntityCreeper['爬行者'/211, l='MpServer', x=165.07, y=25.00, z=-119.17], EntityCreeper['爬行者'/212, l='MpServer', x=168.47, y=26.00, z=-114.83], EntityBat['蝙蝠'/213, l='MpServer', x=164.25, y=41.82, z=-112.68], EntityChicken['鸡'/214, l='MpServer', x=173.50, y=64.00, z=-52.50], EntityChicken['鸡'/215, l='MpServer', x=170.50, y=65.00, z=-51.50], EntityZombie['僵尸'/87, l='MpServer', x=55.22, y=37.00, z=-82.49], EntityChicken['鸡'/88, l='MpServer', x=62.50, y=64.00, z=-69.50], EntityChicken['鸡'/216, l='MpServer', x=169.50, y=66.00, z=-49.50], EntityChicken['鸡'/217, l='MpServer', x=177.13, y=73.00, z=-45.45], EntitySkeleton['骷髅'/90, l='MpServer', x=58.50, y=21.00, z=-39.50], EntityZombie['僵尸'/91, l='MpServer', x=63.45, y=45.00, z=-0.80], EntityVillager['村民'/96, l='MpServer', x=56.50, y=68.00, z=18.50], EntitySkeleton['骷髅'/224, l='MpServer', x=181.50, y=21.00, z=-121.50], EntityVillager['村民'/97, l='MpServer', x=56.50, y=68.00, z=19.50], EntityZombie['僵尸'/225, l='MpServer', x=173.50, y=13.00, z=-101.78], EntityZombie['僵尸'/226, l='MpServer', x=173.30, y=15.00, z=-93.33], EntitySkeleton['骷髅'/227, l='MpServer', x=185.50, y=53.00, z=-85.50], EntityPlayerSP['HeavenTyh'/356, l='MpServer', x=133.20, y=64.00, z=-57.15], EntityCow['牛'/234, l='MpServer', x=193.55, y=63.00, z=-122.77], EntitySkeleton['骷髅'/107, l='MpServer', x=67.50, y=28.00, z=-65.29], EntityCow['牛'/235, l='MpServer', x=200.17, y=67.00, z=-126.52], EntityEnderman['末影人'/108, l='MpServer', x=66.66, y=50.00, z=-65.36], EntityCow['牛'/236, l='MpServer', x=195.50, y=65.00, z=-132.50], EntityChicken['鸡'/109, l='MpServer', x=64.38, y=64.00, z=-66.62], EntityBat['蝙蝠'/237, l='MpServer', x=196.27, y=13.54, z=-121.46], EntityChicken['鸡'/110, l='MpServer', x=59.84, y=64.00, z=-62.72], EntityBat['蝙蝠'/238, l='MpServer', x=211.81, y=27.06, z=-109.04], EntityChicken['鸡'/111, l='MpServer', x=70.16, y=67.00, z=-78.42], EntityEnderman['末影人'/239, l='MpServer', x=203.50, y=37.00, z=-110.50], EntityCreeper['爬行者'/112, l='MpServer', x=71.50, y=28.00, z=-60.50], EntityCreeper['爬行者'/240, l='MpServer', x=192.50, y=15.00, z=-89.50], EntitySkeleton['骷髅'/113, l='MpServer', x=72.56, y=64.00, z=-58.82], EntityChicken['鸡'/241, l='MpServer', x=206.81, y=71.00, z=-21.59], EntitySkeleton['骷髅'/114, l='MpServer', x=66.39, y=45.00, z=7.72], EntitySkeleton['骷髅'/115, l='MpServer', x=66.50, y=46.00, z=11.50], EntityBat['蝙蝠'/116, l='MpServer', x=68.33, y=45.73, z=6.30], EntityBat['蝙蝠'/117, l='MpServer', x=74.84, y=31.01, z=17.93], EntityChicken['鸡'/245, l='MpServer', x=203.76, y=64.00, z=18.89], EntityZombie['僵尸'/252, l='MpServer', x=210.46, y=37.00, z=-111.74], EntityChicken['鸡'/125, l='MpServer', x=94.50, y=63.00, z=-134.50], EntityChicken['鸡'/126, l='MpServer', x=90.87, y=63.00, z=-129.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 420346032 bytes (400 MB) / 1604845568 bytes (1530 MB) up to 8306819072 bytes (7922 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8912m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                  | Signature                                |
	|:------ |:----------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                           | None                                     |
	| LCHIJA | opframe           | 1.4.0        | OnlinePicFrame_v1.4.40_mc1.12.2.jar     | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.29_mc1.12.2.jar      | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.29_mc1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame you need the newest beta.
