### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by RJHG56** [CreativeMD/OnlinePictureFrame#61]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 11/20/20 3:08 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/opf/OPFrame$1
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.opf.OPFrame$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/client/gui/handler/LittleGuiHandler
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.client.gui.handler.LittleGuiHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 222282296 bytes (211 MB) / 503316480 bytes (480 MB) up to 15804137472 bytes (15072 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx15061M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                 | Source                                             | Signature                                |
	|:----- |:-------------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                  | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LC    | mcp                        | 9.42                    | minecraft.jar                                      | None                                     |
	| LC    | FML                        | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                      | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy          | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LC    | littletilescore            | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LC    | openmodscore               | 0.12.2                  | minecraft.jar                                      | None                                     |
	| LC    | obfuscate                  | 0.4.2                   | minecraft.jar                                      | None                                     |
	| LC    | techguns_core              | 1.12.2-1.0              | minecraft.jar                                      | None                                     |
	| LC    | uncraftingtable            | 1.8-beta6               | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
	| LC    | jei                        | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LC    | abyssalcraft               | 1.10.3                  | AbyssalCraft-1.12.2-1.10.3.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LC    | craftstudioapi             | 1.0.0                   | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LC    | harvestcraft               | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LC    | animania                   | 2.0.0.23                | animania-1.12.2-base-2.0.0.23.jar                  | None                                     |
	| LC    | applecore                  | 3.4.0                   | AppleCore-mc1.12.2-3.4.0.jar                       | None                                     |
	| LC    | appleskin                  | 1.0.14                  | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LC    | crafttweaker               | 4.1.20                  | CraftTweaker2-1.12-4.1.20.601.jar                  | None                                     |
	| LC    | athenaeum                  | 1.12.2-1.19.2           | athenaeum-1.12.2-1.19.2.jar                        | None                                     |
	| LC    | quark                      | r1.6-179                | Quark-r1.6-179.jar                                 | None                                     |
	| LC    | autoreglib                 | 1.3-32                  | AutoRegLib-1.3-32.jar                              | None                                     |
	| LC    | baubles                    | 1.5.2                   | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LC    | bloodmoon                  | 1.5.3                   | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | compactstorage             | 3.1                     | CompactStorage-3.1-12.jar                          | None                                     |
	| LC    | mantle                     | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LC    | tconstruct                 | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LC    | conarm                     | 1.2.5.9                 | conarm-1.12.2-1.2.5.9.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | ctgui                      | 1.0.0                   | CraftTweaker2-1.12-4.1.20.601.jar                  | None                                     |
	| LC    | crafttweakerjei            | 2.0.3                   | CraftTweaker2-1.12-4.1.20.601.jar                  | None                                     |
	| L     | opframe                    | 1.4.0                   | OnlinePicFrame_v1.4.40_mc1.12.2 (1).jar            | None                                     |
	| L     | creativecore               | 1.10.0                  | CreativeCore_v1.10.34_mc1.12.2.jar                 | None                                     |
	| L     | customspawner              | 3.11.4                  | CustomMobSpawner-3.11.5.jar                        | None                                     |
	| L     | dropt                      | 1.12.2-1.18.0           | dropt-1.12.2-1.18.0.jar                            | None                                     |
	| L     | mocreatures                | 12.0.5                  | DrZharksMoCreaturesMod-12.0.5.jar                  | None                                     |
	| L     | dynamictrees               | 1.12.2-0.9.21           | DynamicTrees-1.12.2-0.9.21.jar                     | None                                     |
	| L     | ebwizardry                 | 4.3.1                   | ElectroblobsWizardry-4.3.1-MC1.12.2.jar            | None                                     |
	| L     | eyesinthedarkness          | 0.0.5                   | EyesInTheDarkness-0.0.5.jar                        | None                                     |
	| L     | waila                      | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| L     | jeresources                | 0.9.2.60                | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| L     | littletiles                | 1.5.0                   | LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar          | None                                     |
	| L     | llibrary                   | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                         | None                                     |
	| L     | mowziesmobs                | 1.5.8                   | mowziesmobs-1.5.8.jar                              | None                                     |
	| L     | multimob                   | 1.0.5                   | multimob-1.0.5.jar                                 | None                                     |
	| L     | naturescompass             | 1.8.5                   | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
	| L     | openmods                   | 0.12.2                  | OpenModsLib-1.12.2-0.12.2.jar                      | None                                     |
	| L     | openblocks                 | 1.8.1                   | OpenBlocks-1.12.2-1.8.1.jar                        | None                                     |
	| L     | patchouli                  | 1.0-22                  | Patchouli-1.0-22.jar                               | None                                     |
	| L     | primitivemobs              | 1.2.3a                  | primitivemobs-1.2.3a.jar                           | None                                     |
	| L     | punchmenot                 | 1.1                     | Punch+Me+Not+1.3-1.12.jar                          | None                                     |
	| L     | pyrotech                   | 1.12.2-1.4.34           | pyrotech-1.12.2-1.4.34.jar                         | None                                     |
	| L     | xreliquary                 | 1.12.2-1.3.4.796        | Reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
	| L     | roguelike                  | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| L     | ruins                      | 17.2                    | Ruins-1.12.2.jar                                   | None                                     |
	| L     | silentlib                  | 3.0.13                  | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
	| L     | scalinghealth              | 1.3.37                  | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
	| L     | simpledifficulty           | 0.3.3                   | SimpleDifficulty-1.12.2-0.3.3.jar                  | None                                     |
	| L     | spiceoflife                | 1.3.12                  | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
	| L     | techguns                   | 2.0.2.0                 | techguns-1.12.2-2.0.2.0_pre3.2.jar                 | None                                     |
	| L     | tlauncher_custom_cape_skin | 1.4                     | tlskincape_1.12.2-1.4.jar                          | None                                     |
	| L     | vehicle                    | 0.44.1                  | vehicle-0.44.1-mc1.12.2 (1).jar                    | None                                     |
	| L     | immersiveengineering       | 0.12-98                 | ImmersiveEngineering-0.12-98.jar                   | None                                     |
	| L     | hungeroverhaul             | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 452.41' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Comment by CreativeMD** [comment]
Use the newest beta of OnlinePictureFrame.
