### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mr-mw** [CreativeMD/OnlinePictureFrame#66]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 3/1/21 8:13 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/utils/math/box/AlignedBox
	at com.creativemd.opf.OPFrame.<clinit>(OPFrame.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.utils.math.box.AlignedBox
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.opf.OPFrame.<clinit>(OPFrame.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 379264360 bytes (361 MB) / 939524096 bytes (896 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                     | Source                                    | Signature                                |
	|:----- |:-------------------------- |:--------------------------- |:----------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                  | 1.12.2                      | minecraft.jar                             | None                                     |
	| LC    | mcp                        | 9.42                        | minecraft.jar                             | None                                     |
	| LC    | FML                        | 8.0.99.99                   | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                      | 14.23.5.2854                | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy          | 1.0.0                       | minecraft.jar                             | None                                     |
	| LC    | obfuscate                  | 0.4.2                       | minecraft.jar                             | None                                     |
	| LC    | blockcraftery              | 1.12.2-1.3.1                | blockcraftery-1.12.2-1.3.1.jar            | None                                     |
	| LC    | cdm                        | 0.4.1                       | cdm-0.4.1-mc1.12.2.jar                    | None                                     |
	| LC    | cfm                        | 6.3.0                       | cfm-6.3.0-mc1.12.2.jar                    | None                                     |
	| LC    | cgm                        | 0.15.3                      | cgm-0.15.3-mc1.12.2.jar                   | None                                     |
	| LC    | creativecore               | 1.10.0                      | CreativeCore-1.12.2.jar                   | None                                     |
	| LC    | customnpcs                 | 1.12                        | CustomNPCs_1.12.2-(05Jul20) (1)(NEWW}.jar | None                                     |
	| LC    | advancedvanillajavaediiton | 1.0.0                       | Enhanced-Vanilla-Mod-1.12.2.jar           | None                                     |
	| LC    | extrautils2                | 1.0                         | Extra-Utilities-Mod-1.12.2.jar            | None                                     |
	| LC    | imsm                       | 1.12                        | Instant-Massive-Structures-Mod-1.12.2.jar | None                                     |
	| LC    | ism                        | 2.6.1 MC-1.12.2             | ism-2.6.1 MC-1.12.2.jar                   | None                                     |
	| LC    | journeymap                 | 1.12.2-5.7.0                | journeymap-1.12.2-5.7.0.jar               | None                                     |
	| LC    | mcwfurnitures              | 1.0.1                       | Macaws-Furniture-Mod-1.12.2.jar           | None                                     |
	| LC    | malisiscore                | 1.12.2-6.5.1-SNAPSHOT       | MalisisCore-1.12.2.jar                    | None                                     |
	| LC    | malisisblocks              | 1.12.2-6.1.0                | malisisblocks-1.12.2-6.1.0.jar            | None                                     |
	| LC    | malisisdoors               | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar             | None                                     |
	| L     | opframe                    | 1.4.0                       | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar   | None                                     |
	| L     | vbe                        | GRADLE:VERSION-GRADLE:BUILD | Vanilla-Builders-Extension-Mod-1.12.2.jar | None                                     |
	| L     | vehicle                    | 0.44.1                      | vehicle-0.44.1-mc1.12.2.jar               | None                                     |
	| L     | worldedit                  | 6.1.10-SNAPSHOT             | WorldEdit-1.12.2.jar                      | None                                     |
	| L     | xlfoodmod                  | 1.12.2-1.9.2                | XL-Food-Mod-1.12.2.jar                    | None                                     |
	| L     | mysticallib                | 1.12.2-1.9.0                | mysticallib-1.12.2-1.9.0.jar              | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: realistico-19-07-demo.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.281 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by CreativeMD** [comment]
Download CreativeCore from curseforge and all the other mods as well.
